sudo: required
language: go
go:
- 1.6
env:
  global:
  - secure: KoId4EvebjkAA5/ul6ccDjgDjBG9PUgykWqyDNkjW1dRsyrfrHeG2LFFSXuWsgDILu/Giarvt2MPBDOq6u+rx8Ut5jKp9P7A2yKzn0p1h6JXwW4yipV5l85cbQz/NRLjzW6stJOGVSpZ9m6zvcLV6WqIgdWufBDpibFqEgf/uag5nfdr+CvIICglXKYFolj+NSFk6DseKfjODtlpm66Qxb0kbkz6XkrPqZK6GaNVWW3X9JUhYypUu7wdrYSwzCgDhywMDz2WtB1udxNwlWKFW+fQuEXJyrGaXe0omdu3h1qO+AmBLi7PQRLee9D6SsnaeXJ2qbhfANG4Q3oyVR2nSFGuTCX8sRvdKMO37angHYBuev04nYGeZidi3oEVEKpRUuF20RoLPPVvzN6+0NRlmZMmmq9+3QFtL8XOE5Mp0w2S55y0l3oM0DmGOgBYecKI8YqMoPWwKmiQ8aiiiNxcPokFCNDR/Q4EtcoCEXYezINIrjBZuimegyklekvleRuhLhewsetv1eq3vXOk0O2qpM/gYElCIsBgySObW7dfuLCA26u5yI1zBYHU66I7SP7rKlwOoGtUM3zWsfk8md+dIUXRfKyUHrklbfmccHUdeC+TJWlluraJDbtm79V+5QgkybMOwB9gW26iy4x/C4f3Iv+w0CsPs0IyhT/HCtesjv0=
  - secure: ot6wVxmGGFIRboKgpjkKs+fyZSHyeQJOcDL00i4VCbKryN5vCv8B0X0DlEqzwKP4mpLNjAduGlCqlDgAml83poNbpNreJZ/D1F+jfR7vgG6+p3ce0eDfcz2ocHDv/JQ364p3uW05lmfyFHdq+QyiLpEyLMGY+jxhb5OtsvnMB9roWyfkngkxXecDx/OqOVz78yw8w1BHfCT3v/FBLCHJEIBSUnBqWDDxnHUBUwx09RQcBQBuuhIwG5MFErPd7TGTPo/Bp+kX7tHrGbzqIc2Rq+AXY14C2RhXq9Zs5DEzluk8QY3Bg1LmKM2aUuHRgLaEGielrKV3gaB09PgJNxcixZMVpXWMmPDn8HJvtJGwVyB2M5YNoQ4Hl7P6Oy3plKmWKQU+JHJXwKAScOIguDBYJA+Td2CAqc7QWJvpI1zj/65hHgfx/cgNKWGHtDqtK+tfBVWFTh8bCaU9cz0jRH1eWDj8PsFdw4KRfJL96FoQogGlxswbCq4zAfmZEfbMOlXIdAl8iVFOnC1p2gZDcQZ/fql+g+Y3Ny3EQEUHp3Q0fK1oBYn8L4Ux4QG5D3M1nTgC1IJMG7M8bJKmld2WgUqTfXOpi/2k7L3IWQQPpmcIjmpk00YvfR0G+QTHuCLCVjlXAm+7Oj3M0LfY64XGZQlr5KgPZHQEk9/e68w9hgjn2cg=
  - secure: bYDXFhgrm//c+39SkWSpz2JDN2K4EPB9QanBd/JXH0GnE8whEHqzp1rtzEajj+1hq8kf7eX35A8C9e/bunOliIbeaibtCSbMnYxkop0+9NPBySic3u03tuHeM+PLZboUflFx4JjAUznHjdOgausxiZ5MYlESEHSmQBoOj3tfHX2+mXd5nVZC3+YQkjotF/ICHGFfLvPao86PFyXgxaT+wkYyBbGSB68Pb8Z+2geAq30mo/UNt87jylP3uXEJN0U5Ce39yRoZ9/KXKNApinEusSKa7nAJSDJc0rSDBWfnLHMxlP+ZVeUSW8g+CKLvWWExicL86qL06ZxA+SlpAKcj0LPR8KM4s48EtPmDhvDPnMb27sczlDXhdCaHui2u+ZyK2KwwP1qXAOxnQaMhhkGzvjyoCrBUxl6gUL9XDCwgdDhCOgKk4RjSZbvfShc1q9hkSwZ7dSKA6WiUD3/aAO8/0lJhQNQnmJYhwyWeY+csYr8VgVlXw4QvPi+TWlw9C4I/CmhZ3+yW+YSYa0eIm6+SOchvsfgjeVlPUxDIBmsxUck6rzF9BdHe/JCrZuLNR63Ooh5bt18xU15gQixGyC8qy5qHfqfrRWT5nAymKP33nHd+7m6FhDHOgbEV1PuB6bXkpkQDYUzAONafB3sTOpQQ1JiNp6urBBrbVoK2yHnifD0=
  matrix:
  - CONTAINER=compilers-rump-go-hw
  - CONTAINER=compilers-rump-go-xen
  - CONTAINER=compilers-rump-go-hw-no-wrapper
  - CONTAINER=compilers-rump-nodejs-hw
  - CONTAINER=compilers-rump-nodejs-xen
  - CONTAINER=compilers-osv-java
  - CONTAINER=boot-creator
  - CONTAINER=image-creator
  - CONTAINER=vsphere-client
  - CONTAINER=qemu-util

services:
  - docker

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - export PATH=$PATH:$HOME/gopath/bin
  - make
  - bash test/scripts/travis_make_containers.sh
  - export PATH=$PATH:$PWD/_build/

script: ginkgo -r --cover --trace --race --compilers=2
