sudo: required
language: go
go:
  - 1.6

env:
  - CONTAINER=compilers-rump-go-hw
  - CONTAINER=compilers-rump-go-xen
  - CONTAINER=compilers-rump-go-hw-no-wrapper
  - CONTAINER=compilers-rump-nodejs-hw
  - CONTAINER=compilers-rump-nodejs-xen
  - CONTAINER=compilers-osv-java
  - CONTAINER=boot-creator
  - CONTAINER=image-creator
  - CONTAINER=vsphere-client
  - CONTAINER=qemu-util

services:
  - docker

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - export PATH=$PATH:$HOME/gopath/bin
  - bash test/scripts/travis_make_containers.sh
  - go install

script: ginkgo -r --cover --trace --race --compilers=2
