sudo: required
language: go
go:
  - 1.6

services:
  - docker

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - export PATH=$PATH:$HOME/gopath/bin
  - test/scripts/travis_make_containers.sh
  - go install

script: ginkgo -r --cover --trace --race --compilers=2
